apiVersion: v1
kind: ConfigMap
metadata:
  name: policies
  namespace: velero
data:
  policies.yaml: |
    version: v1
    volumePolicies:
    - conditions:
        volumeTypes:
        - emptyDir
      action:
          type: skip
