apiVersion: v1
kind: Secret
metadata:
  name: {{ include "encrypt.fullname" . }}
stringData:
  FAKE_REMOTE_ACCESS_KEY: {{ .Values.app.in.s3AccessKey }}
  FAKE_REMOTE_SECRET_KEY: {{ .Values.app.in.s3SecretKey }}
