apiVersion: v1
kind: Secret
metadata:
  name: {{ include "encrypt.fullname" . }}
stringData:
  rclone.conf: |
    [out_s3]
    type = s3
    use_multipart_uploads = false
    provider = {{ .Values.app.out.provider }}
    access_key_id =  {{ .Values.app.out.s3AccessKey }}
    secret_access_key = {{ .Values.app.out.s3SecretKey }}
    endpoint = {{ .Values.app.out.endpoint }}
    region = {{ .Values.app.out.region }}

    [crypt_out_s3]
    type = crypt
    remote = out_s3:{{ .Values.app.out.bucket_and_prefix }}
    filename_encryption = standard
    directory_name_encryption = true
    password = {{ .Values.app.encryptionKey }}
